USE [master]
GO

/****** Object:  Database [srb_StageDB]    Script Date: 08/12/2014 7:07:45 AM ******/
CREATE DATABASE [srb_StageDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'srb_StageDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\srb_StageDB.mdf' , SIZE = 14400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'srb_StageDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\srb_StageDB_log.ldf' , SIZE = 53248KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [srb_StageDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [srb_StageDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [srb_StageDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [srb_StageDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [srb_StageDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [srb_StageDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [srb_StageDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [srb_StageDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [srb_StageDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [srb_StageDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [srb_StageDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [srb_StageDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [srb_StageDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [srb_StageDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [srb_StageDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [srb_StageDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [srb_StageDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [srb_StageDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [srb_StageDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [srb_StageDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [srb_StageDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [srb_StageDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [srb_StageDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [srb_StageDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [srb_StageDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [srb_StageDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [srb_StageDB] SET  MULTI_USER 
GO

ALTER DATABASE [srb_StageDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [srb_StageDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [srb_StageDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [srb_StageDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [srb_StageDB] SET  READ_WRITE 
GO
